#!/bin/bash
words = []
while True:
  word = input("Enter a word: ")
  if not word:
    break
  words.append(word)

unique_words = []
for word in words:
  if words.count(word) == 1:
    unique_words.append(word)

sort_words = sorted(unique_words)

for word in sort_words:
  print(word)
